[package]
name = "uart_stepper_client"
version = "0.1.0"
edition = "2024"

[dependencies]
uart_sized_package_reader_writer = { path = "../ipcs/uart_sized_package_reader_writer" }
uart_port = { path = "../ipcs/uart_port" }
stepper_service_client = { path = "../clients/stepper_service_client" }
