[package]
name = "uart_sized_package_reader_writer"
version = "0.1.0"
edition = "2024"

[dependencies]
libudev = "0.3.0"
serialport = "4.7.1"

ipc = { path = "../../ipc" }
uart_port = { path = "../uart_port" }