[package]
name = "proto_transformers"
version = "0.1.0"
edition = "2024"

[dependencies]
movement_data = { version = "0.1.0", path = "../../data/movement_data" }
tonic = "0.13.1"
prost = "*"

[build-dependencies]
tonic-build = "0.13.1"