[package]
name = "stepper_service_client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "*"
tonic = "0.13.1"
prost = "*"

ipc = { path = "../../ipc" }
client = { path = "../../client" }
stepper_data = { path = "../../data/stepper_data" }

[dev-dependencies]
uart_sized_package_reader_writer = { path = "../../ipcs/uart_sized_package_reader_writer" }
mockall = "*"

[build-dependencies]
tonic-build = "0.13.1"
