[package]
name = "gcode_processor"
version = "0.1.0"
edition = "2024"

[dependencies]
client = { version = "0.1.0", path = "../client" }
movement_data = { version = "0.1.0", path = "../data/movement_data" }

[dev-dependencies]
mockall = "*"